name: project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #bloc
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  equatable: ^2.0.5
  #storage local
  shared_preferences: ^2.1.0
  #map gelocator google map
  geolocator: ^9.0.2
  #dependency_injector
  get_it: ^7.3.0
  #routing
  go_router: ^7.0.0
  #dartz
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2
  #local
  easy_localization: ^3.0.1
  #local notifications
  flutter_local_notifications: ^14.1.0 
  #internet
  internet_connection_checker: ^1.0.0+1
  #permission
  permission_handler: ^10.2.0
  #http requests
  dio: ^5.1.2
  dio_cache_interceptor: ^3.4.2
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  #images
  image_picker: ^0.8.7+5
  #json notation
  json_annotation: ^4.8.1
  #uni link deep links
  uni_links: ^0.5.1
  mockito: ^5.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.1
  json_serializable: ^6.6.2
   


flutter:


  uses-material-design: true
    #assets images
  assets:
    - assets/images/
    - assets/json/
    - assets/sound/
    - assets/translations/
  #assets fonts


